services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    buildCommand: npm run build
    startCommand: npm run db:deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production