services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run db:deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString